# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

# Build HTML (and optionally PDF/EPUB later)
formats:
  - htmlzip

python:
  install:
    - requirements: docs/requirements.txt